### ISSUE TITLE
OFAC Tool

### ISSUE THREAD

**Issue by AJ-Hagemann** [ScrapeWithYuri/Office-of-Foreign-Assets-Control-OFAC-Search-Tool#1]
When I tried to use the tool I only got access denied error 2. I believe the links for the OFAC List are not correct anymore l. Would you be able you fix it?

**Comment by personal-coding** [comment]
@AJ-Hagemann The main sanctions list was originally accessed via a text file. The treasury website recently removed the text file option, so the program will no longer work.
